open_tagger_server/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :letters
  resources :collections
  resources :repositories
  # resources :property_labels
  # resources :entities
  # resources :places
  # resources :languages
  resources :literals
  resources :entity_types, path: 'entity-types'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :people
  get '/search-entities', to: 'entities#search'
  resources :entities
  get '/letter-dates', to: 'letter_dates#index'
  get '/letter-recipients', to: 'letter_recipients#index'
end

open_tagger_server/app/helpers/litterals_helper.rb
module LitteralsHelper
end

open_tagger_server/app/views/litterals/_form.html.erb
<%= form_with(model: literal, local: true) do |form| %>
  <% if literal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(literal.errors.count, "error") %> prohibited this literal from being saved:</h2>

      <ul>
      <% literal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

open_tagger_server/app/views/litterals/edit.html.erb
<h1>Editing Literal</h1>

<%= render 'form', literal: @literal %>

<%= link_to 'Show', @literal %> |
<%= link_to 'Back', literals_path %>

open_tagger_server/app/views/litterals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Literals</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @literals.each do |literal| %>
      <tr>
        <td><%= link_to 'Show', literal %></td>
        <td><%= link_to 'Edit', edit_literal_path(literal) %></td>
        <td><%= link_to 'Destroy', literal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Literal', new_literal_path %>

open_tagger_server/app/views/litterals/new.html.erb
<h1>New Literal</h1>

<%= render 'form', literal: @literal %>

<%= link_to 'Back', literals_path %>

open_tagger_server/app/views/litterals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_literal_path(@literal) %> |
<%= link_to 'Back', literals_path %>