open_tagger_server/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :letters
  resources :collections
  resources :repositories
  # resources :property_labels
  # resources :entities
  # resources :places
  # resources :languages
  resources :literals
  resources :entity_types, path: 'entity-types'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :people
  get '/search-entities', to: 'entities#search'
  resources :entities
  get '/letter-dates', to: 'letter_dates#index'
  get '/letter-recipients', to: 'letter_recipients#index'
end

open_tagger_server/app/controllers/entity_types_controller.rb
class EntityTypesController < ApplicationController
  before_action :set_entity_type, only: [:show, :edit, :update, :destroy]

  # GET /entity_types
  def index
    if params[:label]
      render json: EntityType.find_by(label: params[:label])
    else
      render json: EntityType.all
    end
  end

  # GET /entity_types/1
  def show
  end

  # GET /entity_types/new
  def new
    @entity_type = EntityType.new
  end

  # GET /entity_types/1/edit
  def edit
  end

  # POST /entity_types
  def create
    @entity_type = EntityType.new(entity_type_params)

    if @entity_type.save
      redirect_to @entity_type, notice: 'Entity type was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /entity_types/1
  def update
    if @entity_type.update(entity_type_params)
      redirect_to @entity_type, notice: 'Entity type was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /entity_types/1
  def destroy
    @entity_type.destroy
    redirect_to entity_types_url, notice: 'Entity type was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity_type
      @entity_type = EntityType.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def entity_type_params
      params.fetch(:entity_type, {})
    end
end

open_tagger_server/app/helpers/entity_types_helper.rb
module EntityTypesHelper
end

open_tagger_server/app/views/entity_types/_form.html.erb
<%= form_with(model: entity_type, local: true) do |form| %>
  <% if entity_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entity_type.errors.count, "error") %> prohibited this entity_type from being saved:</h2>

      <ul>
      <% entity_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

open_tagger_server/app/views/entity_types/edit.html.erb
<h1>Editing Entity Type</h1>

<%= render 'form', entity_type: @entity_type %>

<%= link_to 'Show', @entity_type %> |
<%= link_to 'Back', entity_types_path %>

open_tagger_server/app/views/entity_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entity Types</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entity_types.each do |entity_type| %>
      <tr>
        <td><%= link_to 'Show', entity_type %></td>
        <td><%= link_to 'Edit', edit_entity_type_path(entity_type) %></td>
        <td><%= link_to 'Destroy', entity_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity Type', new_entity_type_path %>

open_tagger_server/app/views/entity_types/new.html.erb
<h1>New Entity Type</h1>

<%= render 'form', entity_type: @entity_type %>

<%= link_to 'Back', entity_types_path %>

open_tagger_server/app/views/entity_types/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_entity_type_path(@entity_type) %> |
<%= link_to 'Back', entity_types_path %>